### ISSUE TITLE
signed_request is coming null from salesforce(summer 15)

### ISSUE THREAD

**Issue by anilreddy411** [forcedotcom/SalesforceCanvasFrameworkSDK#5]
I cloned the git repository "https://github.com/forcedotcom/SalesforceCanvasFrameworkSDK”  and hosted on heroku for Canvas demo. 
For some reason index.jsp is getting the signed request as null from salesforce. (“ This App must be invoked via a signed request!" ). Can you please share any ideas to fix the issue?

**Comment by jthurst01** [comment]
This error means that you are not invoking the app from a canvas app using
a signed request.  In your canvas setup inside salesforce make sure that
the access method is set to "Sigbed Request" and not "OAuth Webflow"

On Wednesday, June 24, 2015, Anil <notifications@github.com> wrote:

> I cloned the git repository "
> https://github.com/forcedotcom/SalesforceCanvasFrameworkSDK” and hosted
> on heroku for Canvas demo.
> For some reason index.jsp is getting the signed request as null from
> salesforce. (“ This App must be invoked via a signed request!" ). Can you
> please share any ideas to fix the issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/forcedotcom/SalesforceCanvasFrameworkSDK/issues/5>.
>


-- 
Jay Hurst
Director, Product Management
salesforce.com
jhurst@salesforce.com
415-536-6270

Sent from my mobile device. Please excuse any spelling errors

**Comment by anilreddy411** [comment]
I have setup the app access method  as "Signed Request (POST)" only
![screen shot 2015-06-23 at 11 08 46 pm](https://cloud.githubusercontent.com/assets/9277678/8323736/37660000-19fd-11e5-86ee-896418485078.png)
.

**Comment by jthurst01** [comment]
You would need to log a support case in order for us to investigate.

On Wednesday, June 24, 2015, Anil <notifications@github.com> wrote:

> I have setup the app access method as "Signed Request (POST)" only
> [image: screen shot 2015-06-23 at 11 08 46 pm]
> <https://cloud.githubusercontent.com/assets/9277678/8323736/37660000-19fd-11e5-86ee-896418485078.png>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/forcedotcom/SalesforceCanvasFrameworkSDK/issues/5#issuecomment-114741655>
> .
>


-- 
Jay Hurst
Director, Product Management
salesforce.com
jhurst@salesforce.com
415-536-6270

Sent from my mobile device. Please excuse any spelling errors

**Comment by jthurst01** [comment]
​The other thing to check is that the app (under setup > manage apps >
connected apps) is set to be "Admin Approved Users are pre-authorized" and
not set to "All users may self-authorize".  In the latter, the user has to
do an OAuth flow initially in order to approve the app...which is not built
into the example you are using​


Jay Hurst
Director, Product Management
salesforce.com
jhurst@salesforce.com
415-536-6270
